using KFS.Application.Interfaces;
using KFS.Domain.Enums;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace KFS.Infrastructure.Pdf;

public class PassPdfRenderer : IPassPdfRenderer
{
    public byte[] RenderSheet(AdminPassType type, string eventName, DateTime eventDate, IReadOnlyList<PassPdfEntry> entries)
    {
        var doc = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(20);
                page.PageColor(Colors.White);
                page.DefaultTextStyle(t => t.FontSize(10));

                page.Header().Text(t =>
                {
                    t.Span($"{type} pass batch — ").Bold();
                    t.Span($"{eventName} ({eventDate:dd MMM yyyy})");
                });

                page.Content().Column(col =>
                {
                    var perRow = 3;
                    for (var i = 0; i < entries.Count; i += perRow)
                    {
                        col.Item().Row(row =>
                        {
                            for (var j = 0; j < perRow; j++)
                            {
                                if (i + j >= entries.Count) { row.RelativeItem(); continue; }
                                var entry = entries[i + j];
                                row.RelativeItem().PaddingBottom(15).Border(1).BorderColor(Colors.Grey.Lighten2)
                                    .Padding(8).Column(cell =>
                                {
                                    cell.Item().AlignCenter().Image(entry.QrPng).WithCompressionQuality(ImageCompressionQuality.High);
                                    cell.Item().PaddingTop(6).AlignCenter().Text(entry.TicketNumber).FontSize(9);
                                    if (entry.SeatsCount > 1)
                                        cell.Item().AlignCenter().Text($"Group of {entry.SeatsCount}").FontSize(8).Italic();
                                    if (!string.IsNullOrWhiteSpace(entry.IssuedToName))
                                        cell.Item().AlignCenter().Text(entry.IssuedToName!).FontSize(9);
                                });
                            }
                        });
                    }
                });

                page.Footer().AlignCenter().Text(t =>
                {
                    t.Span("Generated by KFS Booking · ").FontSize(8).FontColor(Colors.Grey.Medium);
                    t.Span($"{DateTime.UtcNow:yyyy-MM-dd HH:mm} UTC").FontSize(8).FontColor(Colors.Grey.Medium);
                });
            });
        });

        return doc.GeneratePdf();
    }
}
